# Example: n-step behavior in the grid world

* Create a 3x3 grid world
* There are a total number of 9 states the robot can be in
* the initial probability distribution is given by $q$

It is assumed that the robot starts from the center. The probability distribution for the current state is therefore defined. 

In [1]:
import numpy as np
m = 3
m2 = m ** 2 
# initialize the probability distribution
q = np.zeros(m2)
# starting from center
q[m2 // 2] = 1

In [4]:
q

array([0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [2]:
# x1 = 0
# x2 = 1
# xdiff = -1
# ---> right
# xdiff = 1
# ---> left

def is_next_state_reachable(current_state, next_state):
    if np.abs(np.sum(current_state - next_state)) <= 1:
        return True
    else:
        return False



def get_P_own(m, p_up, p_down, p_left, p_right):
    """
    Compute the transition matrix from state s_{t} to s_{t+1}.
    """
    m2 = m ** 2
    P = np.zeros((m2, m2))
    ix_map = {i + 1: np.array([i // m, i % m]) for i in range(m2)}
    for i in range(1):
        i = 4
        for j in range(m2):
            # get coordinates for current state
            current_state = ix_map[i + 1]
            # get coordinates for next state
            next_state = ix_map[j + 1]
            # is next state reachable?
            print(is_next_state_reachable(current_state, next_state))
            
            




                    

Now we are defining a function to calculate the $n \times n$ transition probability matrix

In [5]:
np.zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
def get_P(m, p_up, p_down, p_left, p_right):
    m2 = m ** 2
    P = np.zeros((m2, m2))
    ix_map = {i + 1: (i // m, i % m) for i in range(m2)}
    for i in range(m2):
        for j in range(m2):
            r1, c1 = ix_map[i + 1]
            r2, c2 = ix_map[j + 1]
            rdiff = r1 - r2
            cdiff = c1 - c2
            if rdiff == 0:
                if cdiff == 1:
                    P[i, j] = p_left
                elif cdiff == -1:
                    P[i, j] = p_right
                elif cdiff == 0:
                    if r1 == 0:
                        P[i, j] += p_down
                    elif r1 == m - 1:
                        P[i, j] += p_up
                    if c1 == 0:
                        P[i, j] += p_left
                    elif c1 == m - 1:
                        P[i, j] += p_right
            elif rdiff == 1:
                if cdiff == 0:
                    P[i, j] = p_down
            elif rdiff == -1:
                if cdiff == 0:
                    P[i, j] = p_up
    return P



In [7]:
# Transition probability matrix for 3x3 matrix
P = get_P(3, 0.2, 0.3, 0.25, 0.25)

# [0, down, 0, left, 0, right, 0, up, 0]
# [0, 0.3, 0, 0.25, 0, 0.25, 0, 0.2, 0]

In [8]:
P

array([[0.55, 0.25, 0.  , 0.2 , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.25, 0.3 , 0.25, 0.  , 0.2 , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.25, 0.55, 0.  , 0.  , 0.2 , 0.  , 0.  , 0.  ],
       [0.3 , 0.  , 0.  , 0.25, 0.25, 0.  , 0.2 , 0.  , 0.  ],
       [0.  , 0.3 , 0.  , 0.25, 0.  , 0.25, 0.  , 0.2 , 0.  ],
       [0.  , 0.  , 0.3 , 0.  , 0.25, 0.25, 0.  , 0.  , 0.2 ],
       [0.  , 0.  , 0.  , 0.3 , 0.  , 0.  , 0.45, 0.25, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.3 , 0.  , 0.25, 0.2 , 0.25],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.3 , 0.  , 0.25, 0.45]])

In [5]:
# n-step transition probabilities
n = 1
Pn = np.linalg.matrix_power(P, n)
np.matmul(q, Pn)

array([0.  , 0.3 , 0.  , 0.25, 0.  , 0.25, 0.  , 0.2 , 0.  ])

## Example: Sample path in an ergodic Markov chain

In [6]:
from scipy.stats import itemfreq
s = 4
n = 10 ** 6
visited = [s]

In [7]:
# Simulate the environment
for t in range(n):
    s = np.random.choice(m2, p=P[s, :])
    visited.append(s)

In [8]:
states, frequencies = np.unique(visited, return_counts=True)
for state, frequency in zip(states, frequencies):
    print(f"State: {state}, Frequency: {frequency}, Probability: {frequency / n}")



State: 0, Frequency: 159042, Probability: 0.159042
State: 1, Frequency: 157982, Probability: 0.157982
State: 2, Frequency: 155670, Probability: 0.15567
State: 3, Frequency: 106310, Probability: 0.10631
State: 4, Frequency: 105578, Probability: 0.105578
State: 5, Frequency: 104529, Probability: 0.104529
State: 6, Frequency: 70536, Probability: 0.070536
State: 7, Frequency: 70140, Probability: 0.07014
State: 8, Frequency: 70214, Probability: 0.070214


### Analytically calculating the state values
$$ v = (I - \gamma P)^{-1} P R $$


In [10]:
# Reward vector
R = np.ones(m2 + 1)
R[-1] = 0

In [12]:
P.shape

(9, 9)

In [11]:
# Discount factor 
gamma = 0.9999

inv = np.linalg.inv(np.eye(m2 + 1) - gamma * P)
v = np.matmul(inv, np.matmul(P, R))

ValueError: operands could not be broadcast together with shapes (10,10) (9,9) 